Klass.create( { name:"JavaScript", description:"We will touch the first basic of JavaScript", appointment:DateTime.strptime("05/22/2016 8:00", "%m/%d/%Y %H:%M") , duration:10, user_id:1  })
Klass.create( { name:"React on Rails", description:"Master everything on React on Rails, this is easy!", appointment:DateTime.strptime("05/28/2016 8:00", "%m/%d/%Y %H:%M") , duration:10, user_id:1  })
Klass.create( { name:"Temperature and volatility", description:"Learning how molecules behave in different temperatures of the surroundgingszZ0rz", appointment:DateTime.strptime("05/26/2016 8:00", "%m/%d/%Y %H:%M") , duration:10, user_id:2  })
Klass.create( { name:"Keynes and the Future", description:"Keynes, the cornerstone of the current economy. But how relevant is this theory still?", appointment:DateTime.strptime("05/27/2009 8:00", "%m/%d/%Y %H:%M") , duration:10, user_id:3  })
Klass.create( { name:"Shakespeare in 2016", description:"To beer or not to beer", appointment:DateTime.strptime("05/29/2009 8:00", "%m/%d/%Y %H:%M") , duration:10, user_id:4  })


Subject.create({ name:"Mathematics" })
Subject.create({ name:"Science" })
Subject.create({ name:"Economics" })
Subject.create({ name:"English" })
Subject.create({ name:"Coding" })


Topic.create({ title: "Linear Regression", description:"In statistics, linear regression is an approach for modeling the relationship between a scalar dependent variable y and one or more explanatory variables (or independent variables) denoted X. The case of one explanatory variable is called simple linear regression. For more than one explanatory variable, the process is called multiple linear regression.[1] (This term should be distinguished from multivariate linear regression, where multiple correlated dependent variables are predicted, rather than a single scalar variable.)[2]", subject_id:1, user_id:1 })
Topic.create({ title: "Calculus", description:"Calculus (from Latin calculus, literally)[1] is the mathematical study of change, in the same way that geometry is the study of shape and algebra is the study of operations and their application to solving equations. It has two major branches, differential calculus (concerning rates of change and slopes of curves),[2] and integral calculus (concerning accumulation of quantities and the areas under and between curves);[3] these two branches are related to each other by the fundamental theorem of calculus. Both branches make use of the fundamental notions of convergence of infinite sequences and infinite series to a well-defined limit. Generally, modern calculus is considered to have been developed in the 17th century by Isaac Newton and Gottfried Leibniz. Today, calculus has widespread uses in science, engineering and economics[4] and can solve many problems that elementary algebra alone cannot.", subject_id:1, user_id:1 })
Topic.create({ title: "Molecules", description:"A molecule is an electrically neutral group of two or more atoms held together by chemical bonds.[3][4][5][6][7] Molecules are distinguished from ions by their lack of electrical charge. However, in quantum physics, organic chemistry, and biochemistry, the term molecule is often used less strictly, also being applied to polyatomic ions.", subject_id:2, user_id:2 })
Topic.create({ title: "Practical Session", description:"Burn everythingz!", subject_id:2, user_id:2 })
Topic.create({ title: "Keynes", description:"John Maynard Keynes, 1st Baron Keynes,[1] CB, FBA (/ˈkeɪnz/ kaynz; 5 June 1883 – 21 April 1946), was an English economist whose ideas fundamentally changed the theory and practice of macroeconomics and the economic policies of governments. He built on and greatly refined earlier work on the causes of business cycles, and is widely considered to be one of the most influential economists of the 20th century and the founder of modern macroeconomics.", subject_id:3, user_id:3 })
Topic.create({ title: "Shakespeare", description:"William Shakespeare (/ˈʃeɪkspɪər/;[1] 26 April 1564 (baptised) – 23 April 1616)[nb 1] was an English poet, playwright, and actor, widely regarded as the greatest writer in the English language and the world's pre-eminent dramatist.[2] He is often called England's national poet, and the Bard of Avon.[3][nb 2] His extant works, including collaborations, consist of approximately 38 plays,[nb 3] 154 sonnets, two long narrative poems, and a few other verses, some of uncertain authorship. His plays have been translated into every major living language and are performed more often than those of any other playwright.", subject_id:4, user_id:4 })
Topic.create({ title: "React on Rails", description:"React and Ruby on Rails play very nicely together if you are using the react-rails gem. Using react-rails, you can easily drop in React components throughout your Rails application. In this lesson, we will get react-rails installed and create our first React component.", subject_id:5, user_id:3 })
Topic.create({ title: "JavaScript", description:"JavaScript (/ˈdʒɑːvəˌskrɪpt/[5]) is a high-level, dynamic, untyped, and interpreted programming language.[6] It has been standardized in the ECMAScript language specification.[7] Alongside HTML and CSS, it is one of the three core technologies of World Wide Web content production; the majority of websites employ it and it is supported by all modern Web browsers without plug-ins.", subject_id:5, user_id:1 })


User.create({ name:"Michaelus", last_name:"Farr", city:"Amsterdam", postalcode:"1092VC", email:"michfarr@gmail.com", password:"michfarr", password_confirmation:"michfarr"})
User.create({ name:"Laurentius", last_name:"Weening", city:"Amstelveen", postalcode:"1121AB", email:"laurentius@gmail.com", password:"laurenceweening", password_confirmation:"laurenceweening"})
User.create({ name:"Brian", last_name:"Lens", city:"Amsterdam", postalcode:"1092VC", email:"brian@stutor.nl", password:"brianlens", password_confirmation:"brianlens"})
